### ISSUE TITLE
Getting "undefined" message when installing (Win10)

### ISSUE THREAD

**Issue by r00tw00t** [peteheist/irtt#16]
Hello, I'm getting this message when installing: 

> C:\Go>go get -u github.com/heistp/irtt/
> C:\Users\user\go\src\github.com\heistp\irtt\irtt_server.go:200:16: undefined: syslog.Writer

Any ideas?

**Comment by heistp** [comment]
Sorry, I hadn't realized that this package isn't even implemented in Windows. I'll find a workaround, hope to commit it this weekend. Thanks for the report. :)

**Comment by r00tw00t** [comment]
Ah okay, thank you for looking into it :)

**Comment by heistp** [comment]
This should work on Windows now, but I'd be glad if anyone can confirm it as I lost my Win 10 VM. :|

**Comment by tommyorndorff** [comment]
Confirmed -- compiled on an OS X host with `./build.sh windows` and moved over to a Windows 10 desktop machine.  Runs fine and looks accurate.

Thanks!

**Comment by heistp** [comment]
Great, thanks for checking it!
