### ISSUE TITLE
Allow specifying bind interfaces in addition to addresses

### ISSUE THREAD

**Issue by tohojo** [peteheist/irtt#3]
When deploying irtt to my testbed, I have several boxes with the same interface names but with diffent IPs assigned to each interface. It would be useful to be able to specify the interface name to -b instead of the address, since I can then just reuse the same systemd unit file.

**Comment by heistp** [comment]
Good idea, and presumably if the interface has multiple IPs, you’d expect it to listen on each? Shouldn’t be difficult, I can probably look at it tonight or tomorrow...

**Comment by heistp** [comment]
You can now do: `irtt server -b %eth0` for example, or use * in the interface name as a wildcard, like `%eth*`.

The default bind address is now "%*" so people won't see that pesky warning, unless they've actively specified a bind address with an unspecified IP on a box with multiple IPs.

This was a bunch of changed and new code and I only tested on a few boxes, so re-open with any problems...

**Comment by tohojo** [comment]
Awesome, thanks! :)
