### ISSUE TITLE
README.md `go get` is deprecated

### ISSUE THREAD

**Issue by gwhiteCL** [peteheist/irtt#40]
Step 2 of: 
https://github.com/heistp/irtt#installation

recommends the use of `go get -u github.com/heistp/irtt/cmd/irtt` to install irtt

this command fails for me, with a message that `go get` is no longer supported outside a module.  Apparently this method is deprecated as of go 1.17 (see https://go.dev/doc/go-get-install-deprecation).  The error message helpfully suggests using a `go install` command, which worked:

`go install github.com/heistp/irtt/cmd/irtt@latest`

I suggest updating README.md to reference this command instead of `go get`

**Comment by heistp** [comment]
Fixed, thanks...
