### ISSUE TITLE
Out of order command line parameters are silently ignored

### ISSUE THREAD

**Issue by tohojo** [peteheist/irtt#6]
I've been bitten by this a couple of times now, and got annoyed enough to open a bug.

Basically, this will work:

```
irtt client -d 5s localhost
```

whereas this will appear to work but will silently ignore the parameter and keep running for an hour:

```
irtt client localhost -d 5s
```

Ideally, the order of parameters shouldn't matter. But if the switches are required to be at the beginning, 
at least an error should be raised if they are not...

**Comment by heistp** [comment]
At least it prints the usage. I moved up the earlier task to look for something GNU compatible when I get a chance. I know that might break current usage but it annoys me too, at this point the executable is almost 3 megs minimized anyway and maybe I can find something small enough...

**Comment by tohojo** [comment]
Yeah, much better; thanks :)
